[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
multisig = "3zXKff5skVoTMLRhPAPM6TDfzrsLtZwozsYabjxdqTU9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.testnet.soo.network/rpc"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
